export const CLEAR_STORE = 'CLEAR_STORE';
export const SET_LOADER = 'SET_LOADER';
export const SET_COLOR_MODE = 'SET_COLOR_MODE';
export const SET_SNACKBAR = 'SET_SNACKBAR';
export const SET_ACTIONS_DRAWER_VISIBLE = 'SET_ACTIONS_DRAWER_VISIBLE';
export const SET_ACTIONS_DRAWER_CONTENT = 'SET_ACTIONS_DRAWER_CONTENT';
