export const SET_AUTH_RESPONSE = 'SET_AUTH_RESPONSE';
export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_AVATAR_AND_NAME = 'SET_USER_AVATAR_AND_NAME';
